services:
  app:
    image: ghcr.io/ewiiz/api-vahyna:latest
    restart: always
    ports:
      - '127.0.0.1:3335:3333'
    volumes:
      - uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: CHANGE_ME
      POSTGRES_PASSWORD: CHANGE_ME
      POSTGRES_DB: CHANGE_ME
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -q -d CHANGE_ME -U root' ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
  uploads:
