services:
  app:
    image: ghcr.io/ewiiz/api-cosmetics:latest
    restart: always
    ports:
      - '127.0.0.1:3336:3333'
    volumes:
      - uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cosmetics
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5436:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -q -d cosmetics -U root' ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
  uploads:
