services:
  db:
    container_name: CHANGE_ME-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CHANGE_ME
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -q -d CHANGE_ME -U root']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
#    container_name: CHANGE_ME-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3333:3333'
    volumes:
      - uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: package.json
          target: /app
volumes:
  postgres-data:
  uploads:
